config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: [:list] }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def params_list
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Create a new bookmark</h1>

      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="border-bottom fixed-top" id='bovenstuk'>
    <div class="container d-flex align-items-center justify-content-between py-2">
       <p class='mb-0'>
            <span style="font-size: 40px; color: Dodgerblue;">
            <i class="fad fa-dice-d12"></i> movie
            </span>
      </p>
      <a href="lists/new" class="btn btn-primary">
          Add a list
      </a>
    </div>
  </div>
</div>
<div class="titling" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path("abcg4iexjtjp3v1c7kti.jpg") %>') ">
    <div class="container">
      <h1>Keep all your movies listed</h1>
    </div>
  </div>
  </div>
  <div class="container">
    <h2 class="text-center">Your Lists</h2>
    <div class="cards">
        <% @lists.each do |list| %>
          <%= link_to list_path(list) do%>
            <div class='card p-20' style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>'); background-size: cover;">
              <h4><%=list.name%></h4>
            </div>
          <%end%>
        <%end%>

    </div>
  </div>
</div>

<div class="footer">
    <div class="links">
      <span style="font-size: 20px; color: Dodgerblue;">
      <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
      <a href="#"><i class="fab fa-fw fa-github"></i></a>
      <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
      <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
      </span>
      <p>This website was coded with
      <span style="font-size: 25px; color: Dodgerblue;">
      <i class="fas fa-heart"></i>
      </span> at Le Wagon.</p>
    </div>
  </div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Create a new list</h1>

      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
  <div class="titling" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')">
    <h1><%=@list.name%></h1>
  </div>
 <main>
<%@list.movies.each do |movie|%>
  <div href="#" class="moviecard m-1" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://image.tmdb.org/t/p/original/<%=movie.poster_url%>'); background-size: cover;" >
      <div class="inner">
        <h2 class="movietitle"><%= movie.title%></h2>
        <time class="moviesubtitle"><%=movie.overview%><time>
        <p>test</p>
      </div>
  </div>
<%end%>
</main>
<%= link_to 'add a bookmark to list', new_list_bookmark_path(@list) %>
<%= link_to 'back to list', lists_path%>